gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000
    user_identity_field: username
    token_parameter_name: refresh_token
    single_use: true
    return_expiration: true
    return_expiration_parameter_name: expires_in