controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_refresh_token:
  path: /api/token/token-refresh

api_token_invalidate:
  path: /api/auth/logout